//HintName: ProfilingSettingsProvider.g.cs
// <auto-generated>
//
// ╔════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
// ║                                                                                                            ║
// ║    This file was auto-generated by ChronoTrace.SourceGenerators                                            ║
// ║                                                                                                            ║
// ║    This file should not be edited! Manual changes may cause incorrect behavior and will be overwritten.    ║
// ║                                                                                                            ║
// ╠════════════════════════════════════════════════════════════════════════════════════════════════════════════╣
// ║    Generated: 2020-04-29 13:17:19 UTC                                      ChronoTrace version: Testing    ║
// ╚════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
//
// </auto-generated>


namespace ChronoTrace.ProfilingInternals.Settings;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("[ChronoTrace]", "[Testing]")]
internal static class ProfilingSettingsInitializer
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Initialize()
    {
        var dataExportSettings = new global::ChronoTrace.ProfilingInternals.Settings.DataExport.JsonExporterSettings
        {
            OutputPath = @"",
        };
        var settings = new global::ChronoTrace.ProfilingInternals.Settings.ProfilingSettings
        {
            DataExportSettings = dataExportSettings,
        };
        global::ChronoTrace.ProfilingInternals.Settings.ProfilingSettingsProvider.UpdateSettings(settings);
    }
}
