//HintName: ChronoTrace.CompilerUtilities.g.cs
// <auto-generated>
//
// ╔════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
// ║                                                                                                            ║
// ║    This file was auto-generated by ChronoTrace.SourceGenerators                                            ║
// ║                                                                                                            ║
// ║    This file should not be edited! Manual changes may cause incorrect behavior and will be overwritten.    ║
// ║                                                                                                            ║
// ╠════════════════════════════════════════════════════════════════════════════════════════════════════════════╣
// ║    Generated: 2020-04-29 13:17:19 UTC                                      ChronoTrace version: Testing    ║
// ╚════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
//
// </auto-generated>


namespace System.Runtime.CompilerServices;

[global::System.Diagnostics.Conditional("DEBUG")]
[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true, Inherited = false)]
#pragma warning disable CS9113 // ignore warning thrown for unread parameters
public sealed class InterceptsLocationAttribute(int version, string data) : global::System.Attribute;
#pragma warning restore CS9113