//HintName: S_Driver_ProfilingInterceptors.g.cs
// <auto-generated>
//
// ╔════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
// ║                                                                                                            ║
// ║    This file was auto-generated by ChronoTrace.SourceGenerators                                            ║
// ║                                                                                                            ║
// ║    This file should not be edited! Manual changes may cause incorrect behavior and will be overwritten.    ║
// ║                                                                                                            ║
// ╠════════════════════════════════════════════════════════════════════════════════════════════════════════════╣
// ║    Generated: 2020-04-29 13:17:19 UTC                                      ChronoTrace version: Testing    ║
// ╚════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
//
// </auto-generated>


using System.Runtime.CompilerServices;

namespace ProfilingInterceptors;
public static class SProfilingInterceptorExtensions
{
    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(version: 1, data: "TESTING")]
    public static void InterceptDriver(this global::S __ChronoTrace_Subject)
    {
        var __ChronoTrace_Profiling_Context = global::ChronoTrace.ProfilingInternals.ProfilingContextAccessor.Current;
        var __ChronoTrace_Method_Invocation_Id = __ChronoTrace_Profiling_Context.BeginMethodProfiling("Driver");
        try
        {
            __ChronoTrace_Subject.Driver();
        }
        finally
        {
            __ChronoTrace_Profiling_Context.EndMethodProfiling(__ChronoTrace_Method_Invocation_Id);
            __ChronoTrace_Profiling_Context.CollectTraces();
        }
    }

    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(version: 1, data: "TESTING")]
    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(version: 1, data: "TESTING")]
    public static void InterceptBranchAlpha(this global::S __ChronoTrace_Subject)
    {
        var __ChronoTrace_Profiling_Context = global::ChronoTrace.ProfilingInternals.ProfilingContextAccessor.Current;
        var __ChronoTrace_Method_Invocation_Id = __ChronoTrace_Profiling_Context.BeginMethodProfiling("BranchAlpha");
        try
        {
            __ChronoTrace_Subject.BranchAlpha();
        }
        finally
        {
            __ChronoTrace_Profiling_Context.EndMethodProfiling(__ChronoTrace_Method_Invocation_Id);
            __ChronoTrace_Profiling_Context.CollectTraces();
        }
    }

    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(version: 1, data: "TESTING")]
    public static void InterceptAlphaHelper(this global::S __ChronoTrace_Subject)
    {
        var __ChronoTrace_Profiling_Context = global::ChronoTrace.ProfilingInternals.ProfilingContextAccessor.Current;
        var __ChronoTrace_Method_Invocation_Id = __ChronoTrace_Profiling_Context.BeginMethodProfiling("AlphaHelper");
        try
        {
            __ChronoTrace_Subject.AlphaHelper();
        }
        finally
        {
            __ChronoTrace_Profiling_Context.EndMethodProfiling(__ChronoTrace_Method_Invocation_Id);
            __ChronoTrace_Profiling_Context.CollectTraces();
        }
    }

    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(version: 1, data: "TESTING")]
    public static void InterceptBranchBravo(this global::S __ChronoTrace_Subject)
    {
        var __ChronoTrace_Profiling_Context = global::ChronoTrace.ProfilingInternals.ProfilingContextAccessor.Current;
        var __ChronoTrace_Method_Invocation_Id = __ChronoTrace_Profiling_Context.BeginMethodProfiling("BranchBravo");
        try
        {
            __ChronoTrace_Subject.BranchBravo();
        }
        finally
        {
            __ChronoTrace_Profiling_Context.EndMethodProfiling(__ChronoTrace_Method_Invocation_Id);
            __ChronoTrace_Profiling_Context.CollectTraces();
        }
    }

    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(version: 1, data: "TESTING")]
    public static void InterceptBravoHelper(this global::S __ChronoTrace_Subject)
    {
        var __ChronoTrace_Profiling_Context = global::ChronoTrace.ProfilingInternals.ProfilingContextAccessor.Current;
        var __ChronoTrace_Method_Invocation_Id = __ChronoTrace_Profiling_Context.BeginMethodProfiling("BravoHelper");
        try
        {
            __ChronoTrace_Subject.BravoHelper();
        }
        finally
        {
            __ChronoTrace_Profiling_Context.EndMethodProfiling(__ChronoTrace_Method_Invocation_Id);
            __ChronoTrace_Profiling_Context.CollectTraces();
        }
    }

    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(version: 1, data: "TESTING")]
    public static void InterceptCharlieHelper(this global::S __ChronoTrace_Subject)
    {
        var __ChronoTrace_Profiling_Context = global::ChronoTrace.ProfilingInternals.ProfilingContextAccessor.Current;
        var __ChronoTrace_Method_Invocation_Id = __ChronoTrace_Profiling_Context.BeginMethodProfiling("CharlieHelper");
        try
        {
            __ChronoTrace_Subject.CharlieHelper();
        }
        finally
        {
            __ChronoTrace_Profiling_Context.EndMethodProfiling(__ChronoTrace_Method_Invocation_Id);
            __ChronoTrace_Profiling_Context.CollectTraces();
        }
    }
}